version: 2
registries:
  maven-central:
    type: maven-repository
    url: https://repo.maven.apache.org/maven2/
  maven-itemis:
    type: maven-repository
    url: https://artifacts.itemis.cloud/repository/maven-mps/
multi-ecosystem-groups:
  # All these components are released together as part of modelix.core. Update them in a single PR.
  modelix-core:
    schedule:
      interval: "daily"
    open-pull-requests-limit: 20
updates:
  - package-ecosystem: "gradle"
    registries:
      - maven-central
      - maven-itemis
    directory: "/"
    schedule:
      interval: "daily"
    multi-ecosystem-group: "modelix-core"
    patterns:
      - "org.modelix:authorization"
      - "org.modelix:model-client"
      - "org.modelix:model-server"
      - "org.modelix.mps:mps-sync-plugin3"
  - package-ecosystem: "docker"
    directories:
      - "/"
      - "/helm/modelix"
    schedule:
      interval: "daily"
    multi-ecosystem-group: "modelix-core"
    patterns:
      - "modelix/model-server"
      - "modelix/mps-git-import"
    groups:
      # The major version of pgautoupgrade has to match the major version of postgres
      postgres:
        patterns:
          - "postgres"
          - "pgautoupgrade/pgautoupgrade"
  - package-ecosystem: "npm"
    directories:
      - "/dashboard"
      - "/openapi/redocly"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "build(deps)"
      prefix-development: "build(deps)"
    groups:
      npm-minor-and-patch:
        update-types:
          - "minor"
          - "patch"
