org.gradle.caching=true
# The default of 512m isn't enough since the dashboard (node_modules) and the OpenAPI generators are part of the build.
org.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=1g

# Supported MPS versions by Modelix workspaces.
# Docker images are built for each of the versions.
mpsMajorVersions=2024.1,2025.1

# For each supported major MPS version define:
# * The exact MPS version including the minor version.
mpsVersion2024.1=2024.1.1
mpsVersion2025.1=2025.1.2
