# To learn more about the skaffold.yaml schema visit
# https://skaffold.dev/docs/references/yaml/
apiVersion: skaffold/v4beta11
kind: Config
deploy:
  statusCheck: false
  statusCheckDeadlineSeconds: 120
  helm:
    releases:
      - name: dev
        chartPath: helm/modelix
        skipBuildDependencies: true
        recreatePods: false
        wait: true
        setValueTemplates:
          images.workspaceManager.repository: "{{.IMAGE_REPO_modelix_workspace_manager}}"
          images.workspaceManager.tag: "{{.IMAGE_TAG_modelix_workspace_manager}}@{{.IMAGE_DIGEST_modelix_workspace_manager}}"
          images.workspaceJob.repository: "{{.IMAGE_REPO_modelix_workspace_job}}"
          images.workspaceJob.tag: "{{.IMAGE_TAG_modelix_workspace_job}}@{{.IMAGE_DIGEST_modelix_workspace_job}}"
          images.modelServer.repository: "{{.IMAGE_REPO_model_server}}"
          images.modelServer.tag: "{{.IMAGE_TAG_model_server}}@{{.IMAGE_DIGEST_model_server}}"
          images.proxy.repository: "{{.IMAGE_REPO_modelix_proxy}}"
          images.proxy.tag: "{{.IMAGE_TAG_modelix_proxy}}@{{.IMAGE_DIGEST_modelix_proxy}}"
          images.gitImport.repository: "{{.IMAGE_REPO_mps_git_import}}"
          images.gitImport.tag: "{{.IMAGE_TAG_mps_git_import}}@{{.IMAGE_DIGEST_mps_git_import}}"
          images.keycloak.repository: "{{.IMAGE_REPO_modelix_keycloak}}"
          images.keycloak.tag: "{{.IMAGE_TAG_modelix_keycloak}}@{{.IMAGE_DIGEST_modelix_keycloak}}"
        setValues:
          kestra.serviceAccountName: dev-modelix-sa
          ingress:
            hostname: "localhost"
            installController: true
        
requires:
  - path: ../modelix.workspaces/skaffold.yaml
  - path: ../modelix.core/skaffold.yaml
  - path: skaffold-local.yaml
