# To learn more about the skaffold.yaml schema visit
# https://skaffold.dev/docs/references/yaml/
apiVersion: skaffold/v4beta11
kind: Config
build:
  local: {}
  artifacts:
    - image: modelix/modelix-proxy
      context: proxy
deploy:
  statusCheck: false
  statusCheckDeadlineSeconds: 120
  helm:
    releases:
      - name: dev
        chartPath: helm/modelix
        skipBuildDependencies: true
        recreatePods: false
        wait: true
        setValueTemplates:
          images.workspaceManager.repository: "{{.IMAGE_REPO_modelix_modelix_workspace_manager}}"
          images.workspaceManager.tag: "{{.IMAGE_TAG_modelix_modelix_workspace_manager}}@{{.IMAGE_DIGEST_modelix_modelix_workspace_manager}}"
          images.modelServer.repository: "{{.IMAGE_REPO_modelix_model_server}}"
          images.modelServer.tag: "{{.IMAGE_TAG_modelix_model_server}}@{{.IMAGE_DIGEST_modelix_model_server}}"
          images.proxy.repository: "{{.IMAGE_REPO_modelix_modelix_proxy}}"
          images.proxy.tag: "{{.IMAGE_TAG_modelix_modelix_proxy}}@{{.IMAGE_DIGEST_modelix_modelix_proxy}}"
          images.gitImport.repository: "{{.IMAGE_REPO_modelix_mps_git_import}}"
          images.gitImport.tag: "{{.IMAGE_TAG_modelix_mps_git_import}}@{{.IMAGE_DIGEST_modelix_mps_git_import}}"
        setValues:
          kestra.serviceAccountName: dev-modelix-sa
          ingress:
            hostname: "localhost"
            installController: true
        
requires:
  - path: ../modelix.workspaces/skaffold.yaml
  - path: ../modelix.core/skaffold.yaml
