apiVersion: v1
kind: Service
metadata:
  labels:
    component: db
    {{- include "modelix.labels" . | nindent 4 }}
  name: "{{ include "modelix.fullname" . }}-db"
spec:
  ports:
  - name: "5432"
    port: 5432
    targetPort: 5432
  selector:
    component: db
    {{- include "modelix.selectorLabels" . | nindent 4 }}
