apiVersion: v1
kind: Service
metadata:
  labels:
    component: docker-registry
    {{- include "modelix.labels" . | nindent 4 }}
  name: "{{ include "modelix.fullname" . }}-docker-registry"
spec:
  type: NodePort
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
    nodePort: {{ .Values.internalDockerRegistry.nodePort }}
  selector:
    component: docker-registry
    {{- include "modelix.selectorLabels" . | nindent 4 }}
