{{- if .Values.dockerProxy.secret64 -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "modelix.fullname" . }}-docker-secret"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.dockerProxy.secret64 | quote }}
{{- end -}}