apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "modelix.fullname" . }}-keycloak"
  labels:
    component: keycloak
    {{- include "modelix.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: keycloak
      {{- include "modelix.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        component: keycloak
        {{- include "modelix.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: keycloak
        image: "{{ .Values.dockerProxy.prefix }}{{.Values.keycloak.image.repository}}:{{ .Values.keycloak.image.tag | default .Chart.Version }}"
        imagePullPolicy: {{.Values.keycloak.image.pullPolicy}}
        args:
        - "start-dev"
        - --import-realm
        - --http-enabled=true
        - --health-enabled=true
        - --hostname
        - {{ include "modelix.externalKeycloakUrl" . }}
        - --hostname-backchannel-dynamic=true
        - --proxy-headers=xforwarded
        - --hostname-debug=true
        - --db
        - postgres
        - --db-password
        - {{ .Values.db.user }}
        - --db-username
        - {{ .Values.db.user }}
        - --db-url
        - jdbc:postgresql://{{ include "modelix.fullname" . }}-db:5432/
        {{ if .Values.keycloak.optimizedStartup }}
        - --optimized"
        {{ end }}
        env:
        - name: KC_HEALTH_ENABLED
          value: "true"
        - name: KC_LOG_LEVEL
          value: "{{ .Values.keycloak.loglevel }}"
        - name: KC_BOOTSTRAP_ADMIN_USERNAME
          value: "admin"
        - name: KC_BOOTSTRAP_ADMIN_PASSWORD
          value: "{{ .Values.keycloak.adminPassword }}"
        - name: REALM_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: keycloak-client-secret
              name: "{{ include "modelix.fullname" . }}-keycloak-client-secret"
        {{ if .Values.keycloak.debug }}
        - name: DEBUG
          value: "true"
        - name: DEBUG_PORT
          value: "*:8787"
        {{ end }}
        ports:
        - name: http
          containerPort: 8080
        {{ if .Values.keycloak.debug }}
        - name: debug
          containerPort: 8787
        {{ end }}
        startupProbe:
          httpGet:
            path: /health/ready
            port: 9000
          failureThreshold: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 9000
          periodSeconds: 5
          failureThreshold: 6
        livenessProbe:
          httpGet:
            path: /health/live
            port: 9000
          failureThreshold: 6
          periodSeconds: 10
        resources:
          requests:
            memory: "1200Mi"
            cpu: "0.1"
            ephemeral-storage: 500M
          limits:
            memory: "1200Mi"
            cpu: "1.0"
            ephemeral-storage: 1G
        volumeMounts:
          - name: keycloak-volume
            mountPath: /opt/keycloak/data/import
      volumes:
        - name: keycloak-volume
          configMap:
            name: "{{ include "modelix.fullname" . }}-keycloak-configmap"
      {{- include "modelix.pullSecret" . | nindent 6 }}
