apiVersion: v1
kind: Service
metadata:
  labels:
    component: model
    {{- include "modelix.labels" . | nindent 4 }}
  name: "{{ include "modelix.fullname" . }}-model"
spec:
  type: NodePort
  ports:
  - name: "28101"
    port: 28101
    targetPort: 28101
  - name: "debug"
    port: 5071
    targetPort: 5071
  selector:
    component: model
    {{- include "modelix.selectorLabels" . | nindent 4 }}
