apiVersion: v1
kind: Service
metadata:
  labels:
    component: proxy
    {{- include "modelix.labels" . | nindent 4 }}
  name: "{{ include "modelix.fullname" . }}-proxy"
spec:
  type: NodePort
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    component: proxy
    {{- include "modelix.selectorLabels" . | nindent 4 }}
