{{- if .Values.workspaces.enabled  -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    component: workspace-uploads
    {{- include "modelix.labels" . | nindent 4 }}
  name: "{{ include "modelix.fullname" . }}-workspace-uploads"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.workspaces.uploadsStorageSize }}
{{- end -}}
