{{- if .Values.workspaces.enabled  -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    component: workspace-client
    {{- include "modelix.labels" . | nindent 4 }}
  name: "{{ include "modelix.fullname" . }}-workspace-client"
spec:
  type: NodePort
  ports:
  - name: "projector"
    port: 8887
    targetPort: "projector"
  - name: "diff"
    port: 33334
    targetPort: "diff"
  - name: "generator"
    port: 33335
    targetPort: "generator"
  - name: "jvmdebug"
    port: 5071
    targetPort: "jvmdebug"
  - name: "yourkit"
    port: 10001
    targetPort: "yourkit"
  selector:
    component: workspace-client
    {{- include "modelix.selectorLabels" . | nindent 4 }}
{{- end -}}
