{{- if .Values.workspaces.enabled  -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    component: workspace-manager
    {{- include "modelix.labels" . | nindent 4 }}
  name: "{{ include "modelix.fullname" . }}-workspace-manager"
spec:
  type: ClusterIP
  ports:
  - name: "http"
    port: 28104
    targetPort: 28104
  - name: "proxy"
    port: 33332
    targetPort: 33332
  selector:
    component: workspace-manager
    {{- include "modelix.selectorLabels" . | nindent 4 }}
{{- end -}}
