{{- if .Values.workspaces.enabled  -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: workspace-manager
    {{- include "modelix.labels" . | nindent 4 }}
  name: "{{ include "modelix.fullname" . }}-workspace-manager"
spec:
  revisionHistoryLimit: 5
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  selector:
    matchLabels:
      component: workspace-manager
      {{- include "modelix.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        component: workspace-manager
        {{- include "modelix.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: "{{ include "modelix.serviceAccountName" . }}"
      containers:
      - env:
          - name: model_server_url
            value: http://{{ include "modelix.fullname" . }}-model:28101/
          - name: "KUBERNETES_NAMESPACE"
            value: {{ .Release.Namespace }}
          - name: "WORKSPACE_JOB_IMAGE"
            value: "{{ .Values.dockerProxy.prefix }}{{ .Values.workspaces.job.image.repository }}:{{ .Values.workspaces.job.image.tag }}"
          - name: "KUBERNETES_PREFIX"
            value: "{{ include "modelix.fullname" . }}-"
          - name: MODELIX_MAX_BODY_SIZE
            value: "{{ .Values.maxBodySize }}"
          - name: "MODELIX_JWK_FILE_WORKSPACE_MANAGER"
            value: /secrets/jwk/wsmanager/private.pem
          - name: MPS_BASEIMAGE_VERSION
            value: {{ .Values.versions.modelix.vncBaseImage }}
          - name: MPS_BASEIMAGE_NAME
            value: "{{ .Values.dockerProxy.prefix }}modelix/mps-vnc-baseimage"
          - name: DOCKER_REGISTRY_SERVICE_NAME
            value: "{{ include "modelix.fullname" . }}-docker-registry"
          {{- if .Values.dockerProxy.secret64 }}
          - name: DOCKER_CONFIG_SECRET_NAME
            value: "{{ include "modelix.fullname" . }}-docker-secret"
          {{- end }}
          - name: DOCKER_CONFIG_INTERN_REGISTRY_SECRET_NAME
            value: "{{ include "modelix.fullname" . }}-docker-registry-secret"
          - name: WORKSPACE_CLIENT_DEPLOYMENT_NAME
            value: "{{ include "modelix.fullname" . }}-workspace-client"
          - name: WORKSPACE_CLIENT_NAMESPACE
            value: "{{ .Release.Namespace }}"
          - name: WORKSPACE_CLIENT_PREFIX
            value: "{{ include "modelix.fullname" . }}-wsclt-"
          - name: WORKSPACE_DOCKER_REGISTRY
            value: localhost:5000
          - name: INTERNAL_DOCKER_REGISTRY_AUTHORITY
            value: "localhost:{{ .Values.internalDockerRegistry.nodePort }}"
          - name: KESTRA_URL
            value: http://{{ .Release.Name }}-kestra-service:8080/
          - name: GIT_IMPORT_IMAGE
            value: "{{ .Values.dockerProxy.prefix }}{{ .Values.gitImport.image.repository }}:{{ .Values.gitImport.image.tag }}"
          {{- include "modelix.authorizationConfig" . | nindent 10 }}
          {{- include "modelix.commonVariables" . | nindent 10 }}
        image: "{{ .Values.dockerProxy.prefix }}{{ .Values.workspaces.manager.image.repository }}:{{ .Values.workspaces.manager.image.tag }}"
        imagePullPolicy: {{ .Values.workspaces.manager.image.pullPolicy }}
        name: workspace-manager
        ports:
        - containerPort: 28104
          name: "http"
        - containerPort: 33332
          name: "proxy"
        resources: 
          requests:
            memory: "{{ .Values.workspaces.manager.memory | default "600Mi" }}"
            cpu: "0.1"
          limits:
            memory: "{{ .Values.workspaces.manager.memory | default "600Mi" }}"
            cpu: "1.0"
        readinessProbe:
          httpGet:
            path: /health
            port: 28104
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 28104
          initialDelaySeconds: 60
          periodSeconds: 15
          timeoutSeconds: 10
        volumeMounts:
          - mountPath: "/workspace-manager/modelix-workspaces/uploads"
            name: "{{ include "modelix.fullname" . }}-workspace-uploads"
          - mountPath: "/workspace-manager/config"
            name: "{{ include "modelix.fullname" . }}-workspace-config"
          - name: "{{ include "modelix.fullname" . }}-workspace-secret"
            mountPath: /secrets/workspacesecret
            readOnly: true
          - name: "{{ include "modelix.fullname" . }}-workspace-manager-rsa-keys"
            mountPath: /secrets/jwk/wsmanager
            readOnly: true
          - name: workspace-client-templates
            mountPath: /workspace-client-templates
      restartPolicy: Always
      volumes:
        - name: workspace-client-templates
          configMap:
            name: "{{ include "modelix.fullname" . }}-workspace-client-templates"
        - name: "{{ include "modelix.fullname" . }}-workspace-uploads"
          persistentVolumeClaim:
            claimName: "{{ include "modelix.fullname" . }}-workspace-uploads"
        - name: "{{ include "modelix.fullname" . }}-workspace-config"
          persistentVolumeClaim:
            claimName: "{{ include "modelix.fullname" . }}-workspace-config"
        - name: "{{ include "modelix.fullname" . }}-workspace-secret"
          secret:
            secretName: "{{ include "modelix.fullname" . }}-workspace-secret"
            items:
              - key: workspace-secret
                path: workspace-credentials-key.txt
        - name: "{{ include "modelix.fullname" . }}-workspace-manager-rsa-keys"
          secret:
            secretName: "{{ include "modelix.fullname" . }}-workspace-manager-rsa-keys"
            items:
              - key: private
                path: private.pem
      {{- include "modelix.pullSecret" . | nindent 6 }}
{{- end -}}
