FROM caddy:2.11@sha256:3422ce6de165df66534f9b9ba50efaf457114ec961763cc52f5dbdaac2972d73
COPY Caddyfile /etc/caddy/Caddyfile
COPY index.html /usr/share/caddy/
COPY public/ /usr/share/caddy/public/
COPY dashboard/ /usr/share/caddy/modelix/dashboard/
