FROM caddy:2.11@sha256:f2a1290d0463aad60660d4ec134943f183ee2a5f6c3eb7bf32dd984f2f020772
COPY Caddyfile /etc/caddy/Caddyfile
COPY index.html /usr/share/caddy/
COPY public/ /usr/share/caddy/public/
COPY dashboard/ /usr/share/caddy/modelix/dashboard/
