name: Publish

on:
  push:
    tags:
      - '**'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5
        with:
          distribution: temurin
          java-version: 21

      - name: Use tag as version
        run: echo "${GITHUB_REF#refs/*/}" > version.txt

      - name: Setup Gradle
        uses: gradle/gradle-build-action@ac2d340dc04d9e1113182899e983b5400c17cda1 # v3

      - name: Execute Gradle build
        run: ./gradlew assemble

      # Add support for more platforms with QEMU (optional)
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@99012661954931238ded8c8b007157a8430204e1 # v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f87e5991a6d7451dcb8d9637bfbc97413f497069 # v4
        with:
          platforms: linux/amd64,linux/arm64

      - name: Login to Docker Hub
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_KEY }}

      - name: Install Skaffold
        uses: yokawasa/action-setup-kube-tools@b16d49b2c459d33cf9d4c300a220ef0bcdbc730a # v0.14.0
        with:
          setup-tools: |
            skaffold
          skaffold: 2.15.0
      - name: Build and Push Images
        run: skaffold build --filename='skaffold-build.yaml' --push --default-repo="docker.io/modelix" --tag="${GITHUB_REF#refs/*/}"

      - name: Publish Helm Chart
        env:
          ARTIFACTS_ITEMIS_CLOUD_USER: ${{secrets.ARTIFACTS_ITEMIS_CLOUD_USER}}
          ARTIFACTS_ITEMIS_CLOUD_PW: ${{secrets.ARTIFACTS_ITEMIS_CLOUD_PW}}
        run: ./helm/publish.sh